### ISSUE TITLE
[Bug] Exception thrown when running 'craft resave/entries'

### ISSUE THREAD

**Issue by HelgeSverre** [putyourlightson/craft-blitz#115]
There seems to be an issue with either Blitz or another plugin that causes the entries resave command to fail.

Output of ```php craft resave/entries```

```
Resaving 59 entries ...
    - Resaving Homepage (3845) ... done
Exception 'TypeError' with message 'Argument 1 passed to putyourlightson\blitz\Blitz::putyourlightson\blitz\{closure}() must be an instance of craft\events\ElementEvent, instance of craft\events\BatchElementActionEvent given'

in C:\xampp\htdocs\customer-website\vendor\putyourlightson\craft-blitz\src\Blitz.php:251

Stack trace:
#0 [internal function]: putyourlightson\blitz\Blitz->putyourlightson\blitz\{closure}(Object(craft\events\BatchElementActionEvent))
#1 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\Event.php(312): call_user_func(Object(Closure), Object(craft\events\BatchElementActionEvent))
#2 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterResaveElem...', Object(craft\events\BatchElementActionEvent))
#3 C:\xampp\htdocs\customer-website\vendor\craftcms\cms\src\services\Elements.php(785): yii\base\Component->trigger('afterResaveElem...', Object(craft\events\BatchElementActionEvent))
#4 C:\xampp\htdocs\customer-website\vendor\craftcms\cms\src\console\controllers\ResaveController.php(316): craft\services\Elements->resaveElements(Object(craft\elements\db\EntryQuery), true)
#5 C:\xampp\htdocs\customer-website\vendor\craftcms\cms\src\console\controllers\ResaveController.php(180): craft\console\controllers\ResaveController->saveElements(Object(craft\elements\db\EntryQuery))
#6 [internal function]: craft\console\controllers\ResaveController->actionEntries()
#7 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\console\Controller.php(148): yii\base\Controller->runAction('entries', Array)
#10 C:\xampp\htdocs\customer-website\vendor\craftcms\cms\src\console\Controller.php(199): yii\console\Controller->runAction('entries', Array)
#11 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\Module.php(528): craft\console\Controller->runAction('entries', Array)
#12 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('resave/entries', Array)
#13 C:\xampp\htdocs\customer-website\vendor\craftcms\cms\src\console\Application.php(93): yii\console\Application->runAction('resave/entries', Array)
#14 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\console\Application.php(147): craft\console\Application->runAction('resave/entries', Array)
#15 C:\xampp\htdocs\customer-website\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 C:\xampp\htdocs\customer-website\craft(22): yii\base\Application->run()
#17 {main}
```

Offending code:

https://github.com/putyourlightson/craft-blitz/blob/v2/src/Blitz.php#L251

**Comment by putyourlightson** [comment]
Thanks for reporting this! Fixed in version 2.1.4.
