### ISSUE TITLE
Error using local warmer: debug() must be of the type string, null given

### ISSUE THREAD

**Issue by alexroper** [putyourlightson/craft-blitz#154]
### Describe the bug

When I try to use the local warmer to warm the cache, the task fails immediately. I checked the queue.log and found this error: `Argument 1 passed to putyourlightson\blitz\Blitz::debug() must be of the type string, null given`

Full stack trace:
```
2020-01-02 14:42:13 [-][6477][-][error][craft\queue\QueueLogBehavior::afterError]  [2201] Warming Blitz cache (attempt: 1) - Error (time: 1.495s): Argument 1 passed to putyourlightson\blitz\Blitz::debug() must be of the type string, null given, called in /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/drivers/warmers/LocalWarmer.php on line 157
2020-01-02 14:42:13 [-][6477][-][error][TypeError] TypeError: Argument 1 passed to putyourlightson\blitz\Blitz::debug() must be of the type string, null given, called in /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/drivers/warmers/LocalWarmer.php on line 157 and defined in /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/Blitz.php:148
Stack trace:
#0 /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/drivers/warmers/LocalWarmer.php(157): putyourlightson\blitz\Blitz->debug(NULL)
#1 /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/drivers/warmers/LocalWarmer.php(84): putyourlightson\blitz\drivers\warmers\LocalWarmer->_warmUri(Object(putyourlightson\blitz\models\SiteUriModel))
#2 [internal function]: putyourlightson\blitz\drivers\warmers\LocalWarmer->warmUrisWithProgress(Array, Array, NULL)
#3 /[path redacted]/releases/1578004640/vendor/putyourlightson/craft-blitz/src/jobs/DriverJob.php(60): call_user_func(Array, Array, Array, NULL)
#4 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2-queue/src/Queue.php(214): putyourlightson\blitz\jobs\DriverJob->execute(Object(craft\queue\Queue))
#5 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('2201', 'O:36:"putyourli...', '300', 1)
#6 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/queue/Queue.php(96): yii\queue\cli\Queue->handleMessage('2201', 'O:36:"putyourli...', '300', 1)
#7 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/controllers/QueueController.php(86): craft\queue\Queue->run()
#8 [internal function]: craft\controllers\QueueController->actionRun()
#9 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('run', Array)
#12 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#13 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('queue/run', Array)
#14 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('queue/run', Array)
#15 /[path redacted]/releases/1578004640/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /[path redacted]/releases/1578004640/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /[path redacted]/releases/1578004640/web/index.php(21): yii\base\Application->run()
#18 {main}
```

Thinking I could manually set the debug option, I created a config/blitz.php file with debug set to false. But this didn't have any effect.

```
return [
    '*' => [
        'debug' => false,
    ]
];
```

### To reproduce
1. Go to Blitz plugin settings in the control panel.
2. Set Cache Warmer option to "Local Warmer"
3. Go to Utilities > Blitz Cache.
4. Click the "Warm Cache" button.

### Expected behavior
Task queue should start and run thru all site urls.

### Versions
- Plugin version: 3.0.3
- Craft version: 3.3.19

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/c2ee277c1bd68aacc9274d60f1c7b96ae062f376 and will be released on Monday.

**Comment by bencroker** [comment]
By the way, unless you explicitly need the Local Warmer, the Guzzle Warmer is recommended.
