### ISSUE TITLE
Login does not work anymore

### ISSUE THREAD

**Issue by migmake** [putyourlightson/craft-blitz#172]
### Describe the bug
Frontend login does not work anymore with Blitz activated.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Frontend login page" (https://app.evolutionary.co/login)
2. Click on button "ACCES COMPTE"
3. See error message "REQUETE INCORRECTE" (incorrect request / cannot very data sent)

### Expected behaviour
I expect the login to work so the user is logged in and can access the homepage.

### Screenshots
![CleanShot 2020-02-16 at 18 16 37@2x](https://user-images.githubusercontent.com/3531623/74609343-8bb94b80-50e9-11ea-8b98-9c566079e319.jpg)
![CleanShot 2020-02-16 at 18 16 11@2x](https://user-images.githubusercontent.com/3531623/74609345-8f4cd280-50e9-11ea-996a-04a0e6dbe4a0.jpg)

### Logs
```
2020-02-16 18:16:28 - error - yii\web\HttpException:400
yii\web\BadRequestHttpException: Impossible de vérifier votre envoi de données. in /srv/data/web/vhosts/app.evolutionary.co/vendor/yiisoft/yii2/web/Controller.php:187
Stack trace:
#0 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/web/Controller.php(134): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/controllers/UsersController.php(111): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#2 /srv/data/web/vhosts/app.evolutionary.co/vendor/yiisoft/yii2/base/Controller.php(155): craft\controllers\UsersController->beforeAction(Object(yii\base\InlineAction))
#3 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('login', Array)
#4 /srv/data/web/vhosts/app.evolutionary.co/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('login', Array)
#5 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('users/login', Array)
#6 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('users/login', Array)
#7 /srv/data/web/vhosts/app.evolutionary.co/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /srv/data/web/vhosts/app.evolutionary.co/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /srv/data/web/vhosts/app.evolutionary.co/web/index.php(21): yii\base\Application->run()
#10 {main}
2020-02-16 18:16:28 - info - application
$_GET = [
    'p' => 'login'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'users/login'
    'loginName' => 'dsdsqds'
    'password' => ''
]
```

### Versions
- Plugin version: 3.2.0
- Craft version: 3.4.5

**Comment by bencroker** [comment]
You'll need to either exclude the login page from caching, or use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature to make the form work dynamically.

**Comment by migmake** [comment]
Ah ok thanks I did not know that.

Should I do that on every pages that have forms ?

**Comment by bencroker** [comment]
Yes, as statically cached forms will not pass the CSRF validation that is applied to submissions.

**Comment by migmake** [comment]
Ah ok great I got it !
Great plugin by the way :)
Thx.
