### ISSUE TITLE
Foreign key constraint error

### ISSUE THREAD

**Issue by lukasNo1** [putyourlightson/craft-blitz#274]
I updated from 2.3.5 to the most recent version 3.6.12.

Maybe related to https://github.com/putyourlightson/craft-blitz/issues/240 ?
The fix mentioned in 3.6.8 seems not to cover this though.

```
Database Exception: SQLSTATE[HY000]: General error: 1025 Error on rename of './PROJECT/#sql-4c3_2a4ddff' to './PROJECT/blitz_elementcaches' (errno: 150 "Foreign key constraint is incorrectly formed")
The SQL being executed was: DROP INDEX blitz_elementcaches_cacheId_elementId_unq_idx ON blitz_elementcaches

Migration: putyourlightson\blitz\migrations\m200721_120000_add_primary_keys

Output:

> drop index blitz_elementcaches_cacheId_elementId_unq_idx on {{%blitz_elementcaches}} ...Exception: SQLSTATE[HY000]: General error: 1025 Error on rename of './PROJECT/#sql-4c3_2a4ddff' to './PROJECT/blitz_elementcaches' (errno: 150 "Foreign key constraint is incorrectly formed")
The SQL being executed was: DROP INDEX blitz_elementcaches_cacheId_elementId_unq_idx ON blitz_elementcaches (/var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX bli...')
#1 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DROP INDEX bli...')
#2 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/db/Migration.php(507): yii\db\Command->execute()
#3 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/helpers/MigrationHelper.php(118): yii\db\Migration->dropIndex('blitz_elementca...', '{{%blitz_elemen...')
#4 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/putyourlightson/craft-blitz/src/migrations/m200721_120000_add_primary_keys.php(28): craft\helpers\MigrationHelper::dropIndexIfExists('{{%blitz_elemen...', Array, true, Object(putyourlightson\blitz\migrations\m200721_120000_add_primary_keys))
#5 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/db/Migration.php(52): putyourlightson\blitz\migrations\m200721_120000_add_primary_keys->safeUp()
#6 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#7 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m200721_120000_add_primary_keys))
#8 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/services/Updates.php(257): craft\db\MigrationManager->up()
#9 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#10 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('migrate', Array)
#15 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('updater/migrate', Array)
#17 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/web/Application.php(665): craft\web\Application->runAction('updater/migrate')
#18 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/craftcms/cms/src/web/Application.php(232): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/crafter/bootstrap/crafter.php(23): yii\base\Application->run()
#21 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/backend/crafter/bootstrap/start.php(23): CrafterApp->run()
#22 /var/www/vhosts/PROJECT.com/staging.PROJECT.com/current/public/de/index.php(4): require_once('/var/www/vhosts...')
#23 {main}
```

**Comment by lukasNo1** [comment]
Server-Version: 10.1.45-MariaDB

**Comment by bencroker** [comment]
The quickest workaround for this is to uninstall the plugin in the CP, then install. This will remove your plugin settings, so be sure to note them down first.
