### ISSUE TITLE
[Craft4] Cannot access offset of type string on string

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-blitz#396]
### Describe the bug
When I enable blitz caching on my local env I'll get the following error:

`Cannot access offset of type string on string`

```
TypeError: Cannot access offset of type string on string in /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php:382
Stack trace:
#0 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php(429): putyourlightson\blitz\services\CacheRequestService->matchesQueryStringParams(1, '', Array)
#1 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php(406): putyourlightson\blitz\services\CacheRequestService->getIsAllowedQueryStringParam(1, '')
#2 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php(253): putyourlightson\blitz\services\CacheRequestService->getAllowedQueryString(1)
#3 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/putyourlightson/craft-blitz/src/Blitz.php(214): putyourlightson\blitz\services\CacheRequestService->getRequestedCacheableSiteUri()
#4 [internal function]: putyourlightson\blitz\Blitz->putyourlightson\blitz\{closure}(Object(yii\base\Event))
#5 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#6 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\web\\Appli...', 'init', Object(yii\base\Event))
#7 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/src/base/ApplicationTrait.php(1477): yii\base\Component->trigger('init')
#8 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/src/web/Application.php(105): craft\web\Application->_postInit()
#9 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#10 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#11 [internal function]: yii\base\Application->__construct(Array)
#12 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#13 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#14 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#15 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#16 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/bootstrap/bootstrap.php(239): Craft::createObject(Array)
#17 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/bootstrap/web.php(40): require('/Users/david.he...')
#18 /Users/david.hellmann/Development/Private/craftcms-baukasten/web/index.php(20): require('/Users/david.he...')
#19 /Users/david.hellmann/.composer/vendor/laravel/valet/server.php(234): require('/Users/david.he...')
#20 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. enable caching

### Screenshots
![CleanShot 2022-04-08 at 19 00 28](https://user-images.githubusercontent.com/764292/162488224-23aeeab8-fecc-49bd-91c9-a643e39d6797.png)

### Versions
- Plugin version: v4.x-dev
- Craft version: Craft 4 Beta 4

**Comment by davidhellmann** [comment]
Can be closed. Didn't have updated my blitz.php config. Sorry!

**Comment by bencroker** [comment]
Please use a beta release for testing, you are currently just using the latest commit. You'll need to update your included/excluded query string parameters config settings from version beta.2 onwards, see https://github.com/putyourlightson/craft-blitz/blob/v4/CHANGELOG.md
