### ISSUE TITLE
Cache is not generated on local Nitro install

### ISSUE THREAD

**Issue by JeanLucEsser** [putyourlightson/craft-blitz#404]
On a local development setup (Nitro), I can't seem to have Blitz generate the cache.
This is a basic config with `Clear cache and regenerate in a queue job`.
I'm in a dev environment without the debug bar enabled.

When using HTTP Generator and generating the cache, no cache is created and no error is thrown, the queue job is successful.

When using Local Generator and generating the cache, an error is thrown in the queue.log (see below).

In both cases, visiting a page does add it to the cache.

I'm running Craft 4.0.2 and Blitz 4.0.3 (PHP 8.1.4).
I have deactivated all other plugins.

Here is the full stack trace of queue.log:
```
2022-05-16 07:41:01 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [66] Generating Blitz cache (attempt: 1, pid: 14) - Error (time: 0.279s): Uncaught Error in child process or thread with message "Failed opening required '/app/bootstrap.php' (include_path='.:/usr/local/lib/php')" and code "0"; use Amp\Parallel\Sync\ContextPanicError::getOriginalTrace() for the stack trace in the child process or thread {"memory":23598352} 
2022-05-16 07:41:01 [queue.ERROR] [Amp\Parallel\Sync\ContextPanicError] Amp\Parallel\Sync\ContextPanicError: Uncaught Error in child process or thread with message "Failed opening required '/app/bootstrap.php' (include_path='.:/usr/local/lib/php')" and code "0"; use Amp\Parallel\Sync\ContextPanicError::getOriginalTrace() for the stack trace in the child process or thread in /app/vendor/amphp/parallel/lib/Sync/ExitFailure.php:46
Stack trace:
#0 /app/vendor/amphp/parallel/lib/Sync/ExitFailure.php(39): Amp\Parallel\Sync\ExitFailure->createException()
#1 /app/vendor/amphp/parallel/lib/Context/Process.php(232): Amp\Parallel\Sync\ExitFailure->getResult()
#2 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()
#3 /app/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(Object(Amp\Parallel\Sync\ExitFailure))
#4 /app/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, Object(Amp\Parallel\Sync\ExitFailure))
#5 /app/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve(Object(Amp\Parallel\Sync\ExitFailure))
#6 /app/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '\x00\xAD\x10\x00\x00O:29:"Amp\\...')
#7 /app/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve('\x00\xAD\x10\x00\x00O:29:"Amp\\...')
#8 /app/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('\x00\xAD\x10\x00\x00O:29:"Amp\\...')
#9 /app/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('o', Resource id #517, NULL)
#10 /app/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, -0.001)
#11 /app/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#12 /app/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#13 /app/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#14 /app/vendor/amphp/amp/lib/functions.php(229): Amp\Loop::run(Object(Closure))
#15 /app/vendor/putyourlightson/craft-blitz/src/drivers/generators/LocalGenerator.php(123): Amp\Promise\wait(Object(Amp\Coroutine))
#16 [internal function]: putyourlightson\blitz\drivers\generators\LocalGenerator->generateUrisWithProgress(Array, Array)
#17 /app/vendor/putyourlightson/craft-blitz/src/jobs/DriverJob.php(69): call_user_func(Array, Array, Array)
#18 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): putyourlightson\blitz\jobs\DriverJob->execute(Object(craft\queue\Queue))
#19 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(66, 'O:36:"putyourli...', 300, 1)
#20 /app/vendor/craftcms/cms/src/queue/Queue.php(182): yii\queue\cli\Queue->handleMessage(66, 'O:36:"putyourli...', 300, 1)
#21 /app/vendor/craftcms/cms/src/queue/Queue.php(157): craft\queue\Queue->executeJob()
#22 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#23 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#24 /app/vendor/craftcms/cms/src/queue/Queue.php(165): yii\queue\cli\Queue->runWorker(Object(Closure))
#25 /app/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#26 [internal function]: craft\controllers\QueueController->actionRun()
#27 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#29 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#30 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('queue/run', Array)
#31 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('queue/run', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#33 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /app/web/index.php(26): yii\base\Application->run()
#35 {main} {"memory":23598728,"exception":"[object] (Amp\\Parallel\\Sync\\ContextPanicError(code: 0): Uncaught Error in child process or thread with message \"Failed opening required '/app/bootstrap.php' (include_path='.:/usr/local/lib/php')\" and code \"0\"; use Amp\\Parallel\\Sync\\ContextPanicError::getOriginalTrace() for the stack trace in the child process or thread at /app/vendor/amphp/parallel/lib/Sync/ExitFailure.php:46)"} 
```

**Comment by bencroker** [comment]
Can you please update to Blitz 4.0.3 to ensure that you're on the current latest version?

**Comment by JeanLucEsser** [comment]
My bad, I'm already on 4.0.3.

**Comment by bencroker** [comment]
Can you also test with concurrency set to `1`?

**Comment by JeanLucEsser** [comment]
Same with concurrency set to `1`.

**Comment by bencroker** [comment]
It looks like your installation might be missing the main `bootstrap.php` file that Craft 4 ships with: 
https://github.com/craftcms/craft/blob/main/bootstrap.php

Did you perhaps update from an earlier version of Craft 3? It looks like this bootstrap file was added back in March 2021.

**Comment by JeanLucEsser** [comment]
I updated from the latest Craft3 release. Let me check with a fresh Craft4 install and get back to you.

**Comment by bencroker** [comment]
It's the Craft repo (https://github.com/craftcms/craft), rather than the CMS repo, that contains this, so I may have to rework this to accommodate older installations.

**Comment by bencroker** [comment]
I just pushed a fix in https://github.com/putyourlightson/craft-blitz/commit/ce652c4fdbde31f1449a650c3935fcacf08bae1f, in case you'd like to try it out on your original project.

**Comment by JeanLucEsser** [comment]
So it works with a fresh Craft 4 install (has to be Local Generator though).

Your fix seems to be working as well on my original project (still Local Generator only).
I didn't find where that bootstrap file was missing from nor what happened exactly but it works so that's great ;)

Thank you so much for your time.

**Comment by bencroker** [comment]
Glad to hear it, this will be shipped with the next release.
