### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#433]
I get this error in the controlpanel on each save:

> include(/vendor/composer/../putyourlightson/craft-blitz/src/drivers/storage/FileStorage.php): failed to open stream: No such file or directory

The page is saved nicely. What is that?

- craft 3.7.45.1
- blitz 3.12.5

```
yii\base\ErrorException: include(/vendor/composer/../putyourlightson/craft-blitz/src/drivers/storage/FileStorage.php): failed to open stream: No such file or directory in /vendor/composer/ClassLoader.php:571
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'include(/home/k...', '/home/kasparal/...', 571)
#1 /vendor/composer/ClassLoader.php(571): craft\web\ErrorHandler->handleError(2, 'include(/home/k...', '/home/kasparal/...', 571, Array)
#2 /vendor/composer/ClassLoader.php(571): include()
#3 /vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/kasparal/...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('putyourlightson...')
#5 [internal function]: spl_autoload_call('putyourlightson...')
#6 /vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('putyourlightson...')
#7 /vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('putyourlightson...')
#8 /vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('putyourlightson...', Array, Array)
#9 /vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('putyourlightson...', Array, Array)
#10 /vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#11 /vendor/yiisoft/yii2/base/Module.php(769): yii\di\ServiceLocator->get('cacheStorage', false)
#12 /vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('cacheStorage')
#13 /vendor/putyourlightson/craft-blitz/src/services/ClearCacheService.php(89): yii\di\ServiceLocator->__get('cacheStorage')
#14 /vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(486): putyourlightson\blitz\services\ClearCacheService->clearAll()
#15 /vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(216): putyourlightson\blitz\services\RefreshCacheService->refreshAll()
#16 /vendor/putyourlightson/craft-blitz/src/Blitz.php(326): putyourlightson\blitz\services\RefreshCacheService->addElement(Object(craft\elements\GlobalSet))
#17 [internal function]: putyourlightson\blitz\Blitz->putyourlightson\blitz\{closure}(Object(craft\events\ElementEvent))
#18 /vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#19 /vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#20 /vendor/craftcms/cms/src/services/Elements.php(2863): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#21 /vendor/craftcms/cms/src/services/Elements.php(785): craft\services\Elements->_saveElementInternal(Object(craft\elements\GlobalSet), true, true, true)
#22 /vendor/craftcms/cms/src/controllers/GlobalsController.php(273): craft\services\Elements->saveElement(Object(craft\elements\GlobalSet))
#23 [internal function]: craft\controllers\GlobalsController->actionSaveContent()
#24 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#26 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-content', Array)
#27 /vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('globals/save-co...', Array)
#28 /vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction('globals/save-co...', Array)
#29 /vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#30 /vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 /www/index.php(32): yii\base\Application->run()
#32 {main}
```

**Comment by bencroker** [comment]
It looks like one of the plugin files is missing. Please try deleting the `vendor/putyourlightson/craft-blitz` folder and then running `composer install` to regenerate the files.
