### ISSUE TITLE
ErrorException unlink(/www/production/storage/runtime/mutex/...lock): No such file or directory

### ISSUE THREAD

**Issue by carolineboeykens** [putyourlightson/craft-blitz#553]
We are getting a lot of errors (like 832 at the moment) regarding the lock files in the mutex folder.
We tried figuring out what it is trying to do here. For some reason the lock file can not be found?
Can you help us out here?

**Stacktrace:**

```
yii\base\ErrorException: unlink(/www/production/storage/runtime/mutex/dbb25ed5b3f892df17560b2155dc1734.lock): No such file or directory
#48 /www/production/vendor/yiisoft/yii2/mutex/FileMutex.php(161): yii\base\ErrorHandler::handleError
#47 /www/production/vendor/craftcms/cms/src/web/ErrorHandler.php(87): craft\web\ErrorHandler::handleError
#46 [internal](0): unlink
#45 /www/production/vendor/yiisoft/yii2/mutex/FileMutex.php(161): yii\mutex\FileMutex::releaseLock
#44 /www/production/vendor/yiisoft/yii2/mutex/Mutex.php(88): yii\mutex\Mutex::release
#43 /www/production/vendor/craftcms/cms/src/mutex/Mutex.php(75): craft\mutex\Mutex::releaseLock
#42 /www/production/vendor/yiisoft/yii2/mutex/Mutex.php(88): yii\mutex\Mutex::release
#41 /www/production/vendor/craftcms/cms/src/mutex/MutexTrait.php(82): craft\mutex\Mutex::release
#40 /www/production/vendor/putyourlightson/craft-blitz/src/services/GenerateCacheService.php(210): putyourlightson\blitz\services\GenerateCacheService::saveElementQuery
#39 /www/production/vendor/putyourlightson/craft-blitz/src/services/GenerateCacheService.php(155): putyourlightson\blitz\services\GenerateCacheService::addElementQuery
#38 /www/production/vendor/putyourlightson/craft-blitz/src/Blitz.php(255): putyourlightson\blitz\Blitz::putyourlightson\blitz\{closure}
#37 [internal](0): call_user_func
#36 /www/production/vendor/yiisoft/yii2/base/Event.php(312): yii\base\Event::trigger
#35 /www/production/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Component::trigger
#34 /www/production/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2129): craft\elements\db\ElementQuery::beforePrepare
#33 /www/production/vendor/craftcms/cms/src/elements/db/EntryQuery.php(840): craft\elements\db\EntryQuery::beforePrepare
#32 /www/production/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1464): craft\elements\db\ElementQuery::prepare
#31 /www/production/vendor/yiisoft/yii2/db/QueryBuilder.php(227): yii\db\QueryBuilder::build
#30 /www/production/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Query::createCommand
#29 /www/production/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query::all
#28 /www/production/vendor/craftcms/cms/src/db/Query.php(152): craft\db\Query::all
#27 /www/production/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1655): craft\elements\db\ElementQuery::all
#26 /www/production/vendor/craftcms/cms/src/elements/db/ElementQuery.php(605): craft\elements\db\ElementQuery::getIterator
#25 /www/production/vendor/twig/twig/src/Extension/CoreExtension.php(1630): twig_array_map
#24 /www/production/vendor/craftcms/cms/src/web/twig/Extension.php(538): craft\web\twig\Extension::mapFilter
#23 /www/production/storage/runtime/compiled_templates/10/102eac6b3124542951b4f5fc81a0d13351ba926523c866a096de4313d0cfec8e.php(75): __TwigTemplate_42912fd911e50fd2e9a81cd57254dfbe0944d8774aeb70b381c2bb6ef5e9995c::block_content
#22 /www/production/vendor/twig/twig/src/Template.php(182): Twig\Template::displayBlock
#21 /www/production/storage/runtime/compiled_templates/5e/5e9bbaccc0ebd97f6013f7408bfa6876a9dffb67e7c94af3c905ab82e98021ad.php(140): __TwigTemplate_2fae7052e48f25b4e96fc7540e2b02d9d7abcb9b4dd84bb624cff05cfaa76642::doDisplay
#20 /www/production/vendor/twig/twig/src/Template.php(405): Twig\Template::displayWithErrorHandling
#19 /www/production/vendor/twig/twig/src/Template.php(378): Twig\Template::display
#18 /www/production/storage/runtime/compiled_templates/10/102eac6b3124542951b4f5fc81a0d13351ba926523c866a096de4313d0cfec8e.php(49): __TwigTemplate_42912fd911e50fd2e9a81cd57254dfbe0944d8774aeb70b381c2bb6ef5e9995c::doDisplay
#17 /www/production/vendor/twig/twig/src/Template.php(405): Twig\Template::displayWithErrorHandling
#16 /www/production/vendor/twig/twig/src/Template.php(378): Twig\Template::display
#15 /www/production/vendor/twig/twig/src/Template.php(390): Twig\Template::render
#14 /www/production/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\TemplateWrapper::render
#13 /www/production/vendor/twig/twig/src/Environment.php(318): Twig\Environment::render
#12 /www/production/vendor/craftcms/cms/src/web/View.php(408): craft\web\View::renderTemplate
#11 /www/production/vendor/craftcms/cms/src/web/View.php(461): craft\web\View::renderPageTemplate
#10 /www/production/vendor/craftcms/cms/src/web/Controller.php(216): craft\web\Controller::renderTemplate
#9 /www/production/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\controllers\TemplatesController::actionRender
#8 [internal](0): call_user_func_array
#7 /www/production/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 /www/production/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#5 /www/production/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /www/production/vendor/craftcms/cms/src/web/Application.php(295): craft\web\Application::runAction
#3 /www/production/vendor/yiisoft/yii2/web/Application.php(103): yii\web\Application::handleRequest
#2 /www/production/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application::handleRequest
#1 /www/production/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(23): null
```

**Comment by bencroker** [comment]
Are you running the latest version of Blitz? Please provide the specific versions of Blitz and Craft for which this issue is occurring so I can help troubleshoot.

**Comment by carolineboeykens** [comment]
Hi @bencroker , yes, thank you

```
"putyourlightson/craft-blitz": "3.12.7",
 "craftcms/cms": "3.9.1",
```

**Comment by bencroker** [comment]
Thanks. The latest version of Blitz v3 is 3.12.10, in which some minor bugs were fixed. Can you please update to it, refresh the cache and then see if the issue persists?

Also, can you please provide some details as to when exactly these errors occur and where you’re seeing them?

**Comment by carolineboeykens** [comment]
Updated to `3.12.10` but the error keeps appearing.

Mostly the error appears after a deploy when we have a composer update and a Blitz cache refresh.

**Comment by bencroker** [comment]
Can you help me understand how the refresh is triggered after deploy? Is it manual, via a deploy script, cron job, etc.?

**Comment by carolineboeykens** [comment]
Yes, it is with a deploy script:

```
executeCommand "composer install --no-dev" "Installing composer requirements..."
executeCommand "chmod +x ./craft"
executeCommand "./craft migrate/all"
executeCommand "./craft project-config/apply"
executeCommand "./craft clear-caches/all"
executeCommand "./craft blitz/cache/refresh"
```

**Comment by bencroker** [comment]
Thanks, I’ll look into this. Can you also please let me know which cache warmer driver (Guzzle or Local) is being used?

**Comment by carolineboeykens** [comment]
These our are settings in **blitz.php**

```
'cachingEnabled' => true,
'cacheStorageSettings' => [
    'folderPath' => '@webroot/cache/blitz',
    'createGzipFiles' => false,
    'countCachedFiles' => true,
],

// The warmer settings.
'cacheWarmerType' => 'putyourlightson\blitz\drivers\warmers\GuzzleWarmer',
'cacheWarmerSettings' => ['concurrency' => 3],
'clearCacheAutomatically' => true,
'warmCacheAutomatically' => false,
'refreshCacheAutomaticallyForGlobals' => false,
'refreshCacheWhenElementSavedUnchanged' => true,
'refreshCacheWhenElementSavedNotLive' => false,
'queryStringCaching' => 1,
```

**Comment by bencroker** [comment]
Thank you, I'll troubleshoot this locally and let you know what I find.

**Comment by bencroker** [comment]
I’ve been unable to replicate this locally. Are you running Craft on a VPS with a regular file system? And is any ephemeral storage or load balancing being used that may be playing havoc with mutex files?

**Comment by bencroker** [comment]
Closing due to inactivity.

**Comment by carolineboeykens** [comment]
Yes, I'm sorry I did not answer yet. We're looking into this issue with our hosting partner.
It might not be caused by Blitz after all.
Thanks for your research and help here!

**Comment by bencroker** [comment]
Ok, good luck and let me know what you find.

**Comment by Numkil** [comment]
I was able to stop the mutex errors from happening by setting the concurrency to 1 in the blitz configuration. 

I doubt its a blitz problem and much more likely some kind of permission problem on our clients server setup. 

its not ideal but at least our Sentry isn't being spammed anymore every time someone deploys a new change.
