### ISSUE TITLE
[v2.0.0-beta.3.1] clear-caches console command error

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#64]
Hey Ben,

Just an FYI, while the `./craft blitz/cache/warm` console command still seems to be working fine, I'm seeing the below error when running the `./craft clear-caches/all` command.
```
Clearing cache: Blitz cache
Error clearing cache Blitz cache: Calling unknown method: putyourlightson\blitz\services\CacheService::clearCache()
```

I also noticed that if you just call `./craft` to get the list of available console commands, it will error when it hits the `clear-caches/blitz` command:
```
- clear-caches                                     Clear caches via the CLI
    clear-caches/all                               Clear all caches
    clear-caches/asset                             Asset caches
    clear-caches/asset-indexing-data               Asset indexing data
    clear-caches/blitzException 'ReflectionException' with message 'Method putyourlightson\blitz\services\CacheService::clearCache() does not exist'

in /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/console/controllers/ClearCachesController.php:156

Stack trace:
#0 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/console/controllers/ClearCachesController.php(156): ReflectionMethod->__construct(Object(putyourlightson\blitz\services\CacheService), 'clearCache')
#1 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/Controller.php(456): craft\console\controllers\ClearCachesController->getActionMethodReflection(Object(craft\console\actions\ClearCacheAction))
#2 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/console/controllers/ClearCachesController.php(120): yii\console\Controller->getActionHelpSummary(Object(craft\console\actions\ClearCacheAction))
#3 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/controllers/HelpController.php(339): craft\console\controllers\ClearCachesController->getActionHelpSummary(Object(craft\console\actions\ClearCacheAction))
#4 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#5 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#6 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#9 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#10 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#11 /Users/michael.roper/Sites/website-v3/vendor/craftcms/cms/src/console/Application.php(99): yii\console\Application->runAction('', Array)
#12 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('', Array)
#13 /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /Users/michael.roper/Sites/website-v3/craft(43): yii\base\Application->run()
#15 {main}
```

(This is with Blitz v2.0.0-beta.3.1 / Craft v3.1.3 :)

**Comment by putyourlightson** [comment]
Thanks Michael, have fixed this for the next release.
