### ISSUE TITLE
Live preview not working with disabled site

### ISSUE THREAD

**Issue by WHITE-developer** [putyourlightson/craft-blitz#646]
### Bug Report

When you have a site globally disabled in the settings -> sites, the preview function breaks when using `includeDynamic` or `includeCached` in the template. `setCurrentSite` tries `getSiteById` which has the `withDisabled` parameter false.

```
yii\base\InvalidArgumentException: Invalid site: 16 in /var/www/html/vendor/craftcms/cms/src/services/Sites.php:490
Stack trace:
#0 /var/www/html/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php(60): craft\services\Sites->setCurrentSite(16)
#1 /var/www/html/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php(31): putyourlightson\blitz\controllers\IncludeController->getRenderedTemplate()
#2 [internal function]: putyourlightson\blitz\controllers\IncludeController->actionCached()
#3 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('cached', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('blitz/include/c...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('blitz/include/c...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/html/web/index.php(12): yii\base\Application->run()
#11 {main}
```

### Plugin Version

4.14.0

### Craft CMS Version

4.8.5

### PHP Version

8.2.13

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-blitz/commit/7be55f7eeb8beefca2187d7116686879a2b568a8 and released in [4.14.1](https://github.com/putyourlightson/craft-blitz/releases/tag/4.14.1).

**Comment by samuel-clara** [comment]
This seems still be an issue on Blitz 5.10.5
I'm getting an 500 error when opening an entry of a "disabled" site with live preview.

```
[web.ERROR] [yii\base\InvalidArgumentException] Invalid site: 2
{"trace":["#0 /home/.../craft/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php(60): craft\\services\\Sites->setCurrentSite(2)",
"#1 /home/.../craft/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php(31): putyourlightson\\blitz\\controllers\\IncludeController->getRenderedTemplate()",
"#2 [internal function]: putyourlightson\\blitz\\controllers\\IncludeController->actionCached()",
"#3 /home/.../craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
"#4 /home/.../craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)",
"#5 /home/.../craft/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('cached', Array)",
"#6 /home/.../craft/vendor/craftcms/cms/src/web/Application.php(361): yii\\base\\Module->runAction('blitz/include/c...', Array)",
"#7 /home/.../craft/vendor/craftcms/cms/src/web/Application.php(660): craft\\web\\Application->runAction('blitz/include/c...', Array)",
"#8 /home/.../craft/vendor/craftcms/cms/src/web/Application.php(323): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))",
"#9 /home/.../craft/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))",
"#10 /home/.../public_html/index.php(12): yii\\base\\Application->run()",
"#11 {main}"],"memory":3632448,"exception":"[object] (yii\\base\\InvalidArgumentException(code: 0): Invalid site: 2 at /home/.../craft/vendor/craftcms/cms/src/services/Sites.php:504)"}
```

**Comment by bencroker** [comment]
@samuel-clara I just tested locally and it appears to be working. Please open a new issue with the exact steps to reproduce.
