### ISSUE TITLE
Key column 'routeVariable' doesn't exist in table

### ISSUE THREAD

**Issue by michaeldietiker** [putyourlightson/craft-blitz#647]
### Bug Report

Tried to update from Beta 1 to Beta 2 / 3 and get the following error when I run the migration:

```
*** applying m240226_120000_drop_route_variable_hints_and_column
    > drop column routeVariable from table {{%blitz_hints}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'routeVariable' doesn't exist in table
The SQL being executed was: ALTER TABLE `blitz_hints` DROP COLUMN `routeVariable` (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `bl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `bl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(391): yii\db\Command->execute()
#3 /var/www/html/vendor/putyourlightson/craft-blitz/src/migrations/m240226_120000_drop_route_variable_hints_and_column.php(18): yii\db\Migration->dropColumn('{{%blitz_hints}...', 'routeVariable')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): putyourlightson\blitz\migrations\m240226_120000_drop_route_variable_hints_and_column->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(365): yii\console\controllers\BaseMigrateController->migrateUp('m240226_120000_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#18 /var/www/html/craft(13): yii\base\Application->run()
#19 {main}
*** failed to apply m240226_120000_drop_route_variable_hints_and_column (time: 0.017s)
```

### Plugin Version

5.0.0-beta.3

### Craft CMS Version

5.0.0-beta.11

### PHP Version

8.2

**Comment by bencroker** [comment]
Hmm, I’m not sure why that’s the case, but I just released 5.0.0-beta.4 that should hopefully resolve that error. Let me know if that works for you.

**Comment by michaeldietiker** [comment]
Thanks, the migration works now.

`*** applying m240226_120000_drop_route_variable_hints_and_column
    > dropping index on {{%blitz_hints}} if it exists ... done (time: 0.006s)
    > drop column routeVariable from table {{%blitz_hints}} ... done (time: 0.003s)
    > create unique index idx_jzmssaxpeecfqjkueyynrdyykgbdkdssrnck on {{%blitz_hints}} (fieldId,template) ... done (time: 0.003s)
*** applied m240226_120000_drop_route_variable_hints_and_column (time: 0.029s)

*** applying m240310_120000_add_stack_trace
    > add column stackTrace text AFTER `line` to table {{%blitz_hints}} ... done (time: 0.002s)
*** applied m240310_120000_add_stack_trace (time: 0.005s)


2 migrations were applied.

Migrated up successfully.`

**Comment by bencroker** [comment]
Great, thanks for reporting!
