### ISSUE TITLE
Getting unknown property: putyourlightson\blitz\Blitz::outputCache

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#68]
Hey Ben,

Just getting a new error on v2.0.0-beta.5, when it tries to load a cached page (if i clear the cache, the page will load fine once, with subsequent loads failing).

```
2019-01-29 00:50:54 [-][-][6vl3ok7n003sj3mkf6ddo1uvrs][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: putyourlightson\blitz\Blitz::outputCache in /home/forge/www/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /home/forge/www/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('outputCache')
#1 /home/forge/www/vendor/putyourlightson/craft-blitz/src/Blitz.php(154): yii\di\ServiceLocator->__get('outputCache')
#2 /home/forge/www/vendor/putyourlightson/craft-blitz/src/Blitz.php(92): putyourlightson\blitz\Blitz->_processCacheableRequest()
#3 /home/forge/www/vendor/yiisoft/yii2/base/BaseObject.php(109): putyourlightson\blitz\Blitz->init()
#4 /home/forge/www/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#5 /home/forge/www/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('blitz', Object(craft\web\Application), Array)
#6 [internal function]: craft\base\Plugin->__construct('blitz', Object(craft\web\Application), Array)
```

(let me know if you need more stack trace...)

**Comment by putyourlightson** [comment]
Thanks Michael, I've gone ahead and pushed v2.0.0-beta.5.1 as I've made some improvements since the last release and the issue you are having should be resolved too, can you please let me know?
```
composer require putyourlightson/craft-blitz:2.0.0-beta.5.1
```

**Comment by michaelroper** [comment]
Cheers Ben, that did fix it! 👍
