### ISSUE TITLE
MySQL error during update

### ISSUE THREAD

**Issue by ishetnogferre** [putyourlightson/craft-blitz#693]
### Bug Report

Hi, we're trying to update Blitz from 5.4.0 to 5.6.0 and bumping into the error below:

![Screenshot 2024-08-05 at 13 24 06](https://github.com/user-attachments/assets/14440d15-153a-4219-8fe1-3078478949a7)

```
Database Exception: SQLSTATE[HY000]: General error: 3780 Referencing column 'fieldInstanceUid' and referenced column 'id' in foreign key constraint 'fk_jmxybsiuggaqemlpieywecnwspkxzncnvwdu' are incompatible.
The SQL being executed was: ALTER TABLE blitz_elementqueryfields CHANGE fieldInstanceUid fieldInstanceUid char(36) NOT NULL DEFAULT '0'

Migration: putyourlightson\blitz\migrations\m240709_120000_alter_fieldid_column

Output:

> dropping foreign key on {{%blitz_elementqueryfields}} if it exists ... done (time: 0.015s)
> rename column fieldId in table {{%blitz_elementqueryfields}} to fieldInstanceUid ... done (time: 0.007s)
> alter column fieldInstanceUid in table {{%blitz_elementqueryfields}} to char(36) NOT NULL DEFAULT '0' ...Exception: SQLSTATE[HY000]: General error: 3780 Referencing column 'fieldInstanceUid' and referenced column 'id' in foreign key constraint 'fk_jmxybsiuggaqemlpieywecnwspkxzncnvwdu' are incompatible.
The SQL being executed was: ALTER TABLE blitz_elementqueryfields CHANGE fieldInstanceUid fieldInstanceUid char(36) NOT NULL DEFAULT '0' (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE bl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE bl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(431): yii\db\Command->execute()
#3 /var/www/html/vendor/putyourlightson/craft-blitz/src/migrations/m240709_120000_alter_fieldid_column.php(29): yii\db\Migration->alterColumn('{{%blitz_elemen...', 'fieldInstanceUi...', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): putyourlightson\blitz\migrations\m240709_120000_alter_fieldid_column->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m240709_120000_alter_fieldid_column))
#7 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#8 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(499): craft\services\Updates->runMigrations(Array)
#9 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('updater/migrate', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(737): craft\web\Application->runAction('updater/migrate')
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(265): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
#19 {main}
```

### Diagnostics Report

- Craft 5
- Blitz 5.4.0 -> Blitz 5.6.0

**Comment by bencroker** [comment]
That’s strange, the foreign key should be dropped in the migration. What database type and version is the site running?

**Comment by ishetnogferre** [comment]
@bencroker it's on MySQL 8.0.33. Also double-checked if the jobs that were waiting/failed didn't interrupt anything, but still happens with an empty queue.

**Comment by bencroker** [comment]
I can’t explain why the foreign key isn’t being dropped, but I just released [5.6.1](https://github.com/putyourlightson/craft-blitz/releases/tag/5.6.1) which drops the old column and creates a new one, instead of trying to alter it. Can you let me know if that works for you?

**Comment by ishetnogferre** [comment]
Different error this time:

```
Database Exception: SQLSTATE[HY000]: General error: 1828 Cannot drop column 'fieldId': needed in a foreign key constraint 'fk_ahkoqburwokefqydbynyhdtxalxkmxybtwre'
The SQL being executed was: ALTER TABLE blitz_elementqueryfields DROP COLUMN fieldId

Migration: putyourlightson\blitz\migrations\m240709_120000_add_fieldinstanceuid_column

Output:

> drop column fieldId from table {{%blitz_elementqueryfields}} ...Exception: SQLSTATE[HY000]: General error: 1828 Cannot drop column 'fieldId': needed in a foreign key constraint 'fk_ahkoqburwokefqydbynyhdtxalxkmxybtwre'
The SQL being executed was: ALTER TABLE blitz_elementqueryfields DROP COLUMN fieldId (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE bl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE bl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(403): yii\db\Command->execute()
#3 /var/www/html/vendor/putyourlightson/craft-blitz/src/migrations/m240709_120000_add_fieldinstanceuid_column.php(24): yii\db\Migration->dropColumn('{{%blitz_elemen...', 'fieldId')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): putyourlightson\blitz\migrations\m240709_120000_add_fieldinstanceuid_column->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m240709_120000_add_fieldinstanceuid_column))
#7 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#8 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(499): craft\services\Updates->runMigrations(Array)
#9 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('updater/migrate', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(737): craft\web\Application->runAction('updater/migrate')
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(265): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
#19 {main}
```

**Comment by bencroker** [comment]
I reverted dropping the foreign key in [5.6.2](https://github.com/putyourlightson/craft-blitz/releases/tag/5.6.2). If this still doesn’t work then you may have to drop the foreign key manually before running the update.

**Comment by ishetnogferre** [comment]
Had the same error, so uninstalled and re-installed it and that worked 👌

**Comment by benjaminkohl** [comment]
We are trying to update Blitz from 5.2.0 to 5.6.2 and I am seeing a semi-related issue to what was described in [this comment](https://github.com/putyourlightson/craft-blitz/issues/693#issuecomment-2268912364):

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'fieldId' doesn't exist in table
The SQL being executed was: ALTER TABLE craft_blitz_elementfieldcaches DROP COLUMN fieldId
```

I am unsure how to work around that if the migration will continue to attempt dropping a column that doesn't exist.

**Comment by smalomo** [comment]
☝️ seeing the same here going from 5.4.0 to 5.6.2:

`> drop column fieldId from table {{%blitz_elementfieldcaches}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'fieldId' doesn't exist in table`

**Comment by bencroker** [comment]
This error is confusing, as the code to drop the `fieldId` only runs if the column already exists.

https://github.com/putyourlightson/craft-blitz/blob/3b5b233d5876a862a70f71f23aa3e8d79357895f/src/migrations/m240709_120000_add_fieldinstanceuid_column.php#L16-L21

Can you please compare your local version of the migration at `src/migrations/m240709_120000_add_fieldinstanceuid_column.php` with the [5.6.2](https://github.com/putyourlightson/craft-blitz/blob/3b5b233d5876a862a70f71f23aa3e8d79357895f/src/migrations/m240709_120000_add_fieldinstanceuid_column.php) one?

What database type and version is the site running, and can you please check the log files to see if you can find the full stack trace?

**Comment by frankkepler** [comment]
Upgrading from latest Craft 4 Blitz plugin (4.22.0) to latest Craft 5 Blitz plugin (5.6.2) during a Craft 4.11.3 to 5.3.4 upgrade

Local `src/migrations/m240709_120000_add_fieldinstanceuid_column.php` matches with the [5.6.2]

Using DDEV with MariaDB 10.4

Error:
```
*** applying m240709_120000_add_fieldinstanceuid_column
    > dropping foreign key on {{%blitz_elementfieldcaches}} if it exists ... done (time: 0.000s)
    > drop column fieldId from table {{%blitz_elementfieldcaches}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'fieldId' doesn't exist in table
The SQL being executed was: ALTER TABLE `blitz_elementfieldcaches` DROP COLUMN `fieldId` (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `bl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE `bl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(403): yii\db\Command->execute()
#3 /var/www/html/vendor/putyourlightson/craft-blitz/src/migrations/m240709_120000_add_fieldinstanceuid_column.php(19): yii\db\Migration->dropColumn('{{%blitz_elemen...', 'fieldId')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): putyourlightson\blitz\migrations\m240709_120000_add_fieldinstanceuid_column->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240709_120000_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /var/www/html/craft(13): yii\base\Application->run()
#31 {main}
*** failed to apply m240709_120000_add_fieldinstanceuid_column (time: 0.017s)

```

Hopefully this is helpful to the conversation.

**Comment by bencroker** [comment]
Thank you, @frankkepler, and everyone else for reporting this. I’m still unable to explain the cause of the error but I was able to reproduce it using MariaDB and have released a more robust fix in [5.6.3](https://github.com/putyourlightson/craft-blitz/releases/tag/5.6.3).

**Comment by smalomo** [comment]
Thank you @bencroker ! Confirming I was able to update to 5.6.4 without any issues. 🎉

**Comment by bencroker** [comment]
Great!
