### ISSUE TITLE
m240110_120000_clear_out_legacy_cached_element_types - memory limit exhausted, msql server gone

### ISSUE THREAD

**Issue by mandrasch** [putyourlightson/craft-blitz#708]
### Bug Report

Hi, just a heads-up. In recent deployments of latest blitz version we experience

```bash
*** applying m240110_120000_clear_out_legacy_cached_element_types
Error: Allowed memory size of 4395630592 bytes exhausted (tried to allocate 335544320 bytes)
```

And even after increasing PHP memory limit, we experienced a db crash
 
```bash
[...] 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416, 95416) (/app/current/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /app/current/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `oe...')
#1 /app/current/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('DELETE FROM `oe...')
#2 /app/current/vendor/yiisoft/yii2/db/ActiveRecord.php(405): yii\db\Command->execute()
#3 /app/current/vendor/putyourlightson/craft-blitz/src/migrations/m240110_120000_clear_out_legacy_cached_element_types.php(33): yii\db\ActiveRecord::deleteAll(Array)
#4 /app/current/vendor/craftcms/cms/src/db/Migration.php(50): putyourlightson\blitz\migrations\m240110_120000_clear_out_legacy_cached_element_types->safeUp()
#5 /app/current/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /app/current/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240110_120000_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/current/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /app/current/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /app/current/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#12 /app/current/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /app/current/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /app/current/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /app/current/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /app/current/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#17 /app/current/vendor/craftcms/cms/src/console/controllers/UpController.php(66): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/current/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /app/current/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /app/current/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('', Array)
#23 /app/current/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#24 /app/current/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /app/current/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /app/current/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#27 /app/current/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /app/current/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /app/current/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /app/current/craft(30): yii\base\Application->run()
#31 {main}
Error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
```

### Diagnostics Report

Blitz: 4.23.0
Database: MariaDB 10.5

**Comment by bencroker** [comment]
Thanks for reporting this. Fixed in https://github.com/putyourlightson/craft-blitz/commit/f0c3a794b417ba3433f2884f2dfe355f6c23c9a7. Can you let me know if this solves the issue for you? 

You can test it by running `composer require "putyourlightson/craft-blitz:4.x-dev as 4.23.1"`.

**Comment by mandrasch** [comment]
Thanks @bencroker! I see what I can do. Might need to setup a separate staging instance to reproduce and test this properly, could take some time.

**Comment by bencroker** [comment]
Can’t you run it locally, or in what environment did it happen?

**Comment by mandrasch** [comment]
I can try this afternoon locally when I have the real db, currently restoring one site which is down. With a smaller test db, it was no problem (of course) locally. I'll get back to you as soon as I know more.

**Comment by mandrasch** [comment]
- live db where error occured was `mariadb 10.5`

**Locally - without fix**

With MariaDB 10.5 and imported live db (~800MB) in DDEV, `ddev craft up` was successful. Couldn't reproduce locally.

```
*** applying m240110_120000_clear_out_legacy_cached_element_types
*** applied m240110_120000_clear_out_legacy_cached_element_types (time: 118.922s)

*** applying m240212_120000_clear_out_legacy_cached_element_types
*** applied m240212_120000_clear_out_legacy_cached_element_types (time: 4.503s)
```

**Locally - with fix**

```bash
ddev composer require "putyourlightson/craft-blitz:4.x-dev as 4.23.1"
```

Started it, but runs for several minutes now without output ... 🤔 

Update: Had to abort it, no output. 

```
*** applying m240110_120000_clear_out_legacy_cached_element_types 
```

I could give you insights into our table sizes for `blitz_` if this is helpful?

Update: `xyz_blitz_elementcaches` is ~ 590 MB, ~ 13 million rows

**Live project**

Unfortunately it happened today on a project where I can't test it easily on a staging environment with same server setup / database server / RAM. I need to discuss next steps in our team as well.

**Comment by bencroker** [comment]
> Started it, but runs for several minutes now without output ... 🤔

Perhaps the batch size was set too low. Can you test it with a batch size of `100000`?

https://github.com/putyourlightson/craft-blitz/blob/f0c3a794b417ba3433f2884f2dfe355f6c23c9a7/src/migrations/m240110_120000_clear_out_legacy_cached_element_types.php#L20

In production, you can simply delete all rows in the `blitz_elementcaches` table  and clear the cache, which should enable the migration to complete.

**Comment by mandrasch** [comment]
```
ddev composer dumpautoload
ddev craft up

*** applying m240110_120000_clear_out_legacy_cached_element_types
```

I can see the rows getting deleted (via checking SequelAce), but it seems to be slow. ~30 seconds per `100000` batch. 

I [added some debug echos](https://gist.github.com/mandrasch/12ff171953599846cb5338fa93690b84):

```
[2024-09-04 14:18:48] Starting deletion for element type: craft\elements\MatrixBlock
[2024-09-04 14:18:48] Retrieved legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:18:48] Deleting legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:18:51] Deleted 100000 records for type: craft\elements\MatrixBlock
[2024-09-04 14:18:51] Starting deletion for element type: craft\elements\MatrixBlock
[2024-09-04 14:19:25] Retrieved legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:19:25] Deleting legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:19:27] Deleted 100000 records for type: craft\elements\MatrixBlock
[2024-09-04 14:19:27] Starting deletion for element type: craft\elements\MatrixBlock
[2024-09-04 14:20:30] Retrieved legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:20:30] Deleting legacy element IDs for type: craft\elements\MatrixBlock
[2024-09-04 14:20:32] Deleted 100000 records for type: craft\elements\MatrixBlock
[2024-09-04 14:20:32] Starting deletion for element type: craft\elements\MatrixBlock
...
```

But depends on my local CPU/RAM/Docker of course 🤷 

Production - ah good to know, thanks!

**Comment by bencroker** [comment]
30 seconds sounds suspiciously slow, but it will get there at least. I’ll keep this in for the next release. Let me know if you have any issues getting the update to complete in production.

**Comment by mandrasch** [comment]
Thanks, so just to be sure for deployment - this is the way to go? :-) 

1. Use official latest version
2. Clear `blitz_elementcaches` table manually
3. Clear all caches
4. Deploy and run `php craft up`

**Comment by bencroker** [comment]
Clearing the Blitz cache is only required to help regenerate the deleted records, so in this order:

1. Use official latest version
2. Clear blitz_elementcaches table manually
3. Deploy and run `php craft up`
4. Clear the Blitz cache

**Comment by mandrasch** [comment]
Just checked, our deployment currently works like this:

```
craft off --retry=60 &&
craft cache/flush-all &&
craft clear-caches/all

# ... add new / add updated files (composer already built)

craft migrate/all --no-content --interactive=0 &&
craft project-config/apply &&
craft migrate/all --interactive=0 &&
craft on
```

Guess this will work as well (hopefully).

**Comment by bencroker** [comment]
Should do.

**Comment by mandrasch** [comment]
Clearing `blitz_elementcaches` manually before deploying worked ✅
