### ISSUE TITLE
"Refreshing Blitz cache" job fails instantly after saving an entry

### ISSUE THREAD

**Issue by fdeneux** [putyourlightson/craft-blitz#79]
As the issue title states. The issue only occurs when saving ~~the homepage~~ an entry on our production environment, saving ~~the homepage~~ an entry on our staging environment works fine.

Only difference in plugin configuration is the `warmCacheAutomatically` setting that is disabled on staging and enabled on production.

Edit: issue is not related to the homepage, but to all entries. The second job works sometimes after saving an entry twice in a row.

```
The command "/usr/bin/php7.2 craft queue/exec "3129" "1800" "1" "" --verbose=1 --color=0" failed. Exit Code: 1(General error) Working directory: /opt/approot/build.20190308-120358-5f380719 Output:

================ Error Output: ================

Exception 'yii\base\InvalidArgumentException' with message 'Job 3129 must be a JobInterface instance instead of __PHP_Incomplete_Class#1 (
  [__PHP_Incomplete_Class_Name] => 'putyourlightson\\blitz\\jobs\\RefreshCacheJob'
  [cacheIds] => [ 0 => '98' 1 => '124' 2 => '129' 3 => '428' ]
  [elementIds] => [ 0 => 2 ]
  [elementTypes] => [ 0 => 'craft\\elements\\Entry' ]
  [description] => null [craft\queue\BaseJob:_progress] => 0
).' in /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2-queue/src/Queue.php:199 Stack trace:

#0 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('3129', 'O:42:"putyourli...', '1800', '1')
#1 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2-queue/src/cli/Command.php(145): yii\queue\cli\Queue->execute('3129', 'O:42:"putyourli...', '1800', '1', '')
#2 [internal function]: yii\queue\cli\Command->actionExec('3129', '1800', '1', '')
#3 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('exec', Array)
#6 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('exec', Array)
#7 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#8 /opt/approot/build.20190308-120358-5f380719/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('queue/exec', Array)
#9 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#10 /opt/approot/build.20190308-120358-5f380719/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /opt/approot/build.20190308-120358-5f380719/craft(22): yii\base\Application->run()
#12 {main}
```

![Screenshot 2019-03-11 at 15 26 00](https://user-images.githubusercontent.com/2846577/54131210-21e0ee00-4412-11e9-8457-30d0192d0f14.png)

**Comment by fdeneux** [comment]
#65

**Comment by fdeneux** [comment]
Disabling the `warmCacheAutomatically` setting on production fixes the issue, but after the "Refreshing Blitz cache" job finishes the "Warming Blitz cache" job is still triggered?

**Comment by putyourlightson** [comment]
Thanks for reporting this. It should be fixed in the upcoming release. If refresh cache jobs fail in future then check the memory assigned to PHP and consider installing the the [Async Queue](https://github.com/ostark/craft-async-queue) plugin to help avoid memory limit issues.

**Comment by fdeneux** [comment]
Great to hear @putyourlightson . Though I don't think our queue setup caused the issue, we got supervisord set up with four workers that runs `craft queue/listen`. The `runQueueAutomatically` setting is also disabled.

**Comment by putyourlightson** [comment]
Ok we'll take a close look into this.

**Comment by putyourlightson** [comment]
Just released Blitz 2 which should resolve this issue.
